version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb://mongo:27017/urlShortener
    depends_on:
      - redis
      - mongo
    volumes:
      - ./src:/app/src # Optional: for development hot-reloading
    networks:
      - url-shortener-network
  redis:
    image: redis:7
    ports:
      - "6379:6379" # Expose Redis port for local debugging (optional)
    volumes:
      - redis-data:/data
    networks:
      - url-shortener-network
  mongo:
    image: mongo:6
    ports:
      - "27017:27017" # Expose MongoDB port for local debugging (optional)
    volumes:
      - mongo-data:/data/db
    networks:
      - url-shortener-network
volumes:
  redis-data:
  mongo-data:
networks:
  url-shortener-network:
    driver: bridge